name: Main Build

on:
  push:
    branches: [ main ]

jobs:
  functions:
    name: Functions
    runs-on: ubuntu-latest
    env:
      working-directory: ./functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install libraries
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: Install firebase
        run: npm i firebase-tools -g

      - name: Test
        run: | 
          npm test
          npm run lint
        working-directory: ${{env.working-directory}}

      - name: Deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}  
        working-directory: ${{env.working-directory}}  

  test-etl:
    name: ETL
    runs-on: ubuntu-latest
    env:
      working-directory: ./etl
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: ${{env.working-directory}}

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        working-directory: ${{env.working-directory}}

      - name: Test
        run: python -m unittest discover test
        working-directory: ${{env.working-directory}}
